from mcp.server.fastmcp import FastMCP
import json
import os

# 1. Initialize the Server
mcp = FastMCP("MelechDSP Algorithms")

# 2. Load the Index (generated by your ingest script)
DB_PATH = os.path.join(os.path.dirname(__file__), "dsp_index.json")

def load_db():
    try:
        with open(DB_PATH, "r") as f:
            return json.load(f)
    except FileNotFoundError:
        return []

dsp_data = load_db()

# 3. Define the Search Tool
@mcp.tool()
def get_dsp_algorithm(query: str) -> str:
    """
    Search local C++ DSP algorithms by name or functionality.
    Use this when the user asks for specific filters, oscillators, or math helpers.
    """
    results = []
    query = query.lower()
    
    for entry in dsp_data:
        # Simple keyword matching
        if query in entry['algorithm_name'].lower() or query in entry['code_snippet'].lower():
            # Return only relevant metadata to save tokens
            results.append(f"Found: {entry['algorithm_name']} (Latency: {entry['latency_samples']} samples)\nSnippet: {entry['code_snippet'][:500]}...")
            
    if not results:
        return "No matching DSP algorithms found in local index."
        
    return "\n---\n".join(results[:3]) # Limit to top 3 matches

if __name__ == "__main__":
    mcp.run()